import Foundation

/// The app-owned UserDefaults keys known to the migration boundary.
///
/// This inventory is intentionally wider than the blocking metadata allowlist.
/// It includes settings owned by existing sync/lifecycle stores, device-local
/// caches, legacy cleanup, and Keychain compatibility code so the source side
/// is reviewed as a whole before a future coordinator is allowed to activate.
/// It must never be replaced with `dictionaryRepresentation()`: that would
/// include framework and third-party keys that the app does not own.
enum LibrarySettingsSourceInventory {
    /// Keys stored in the main application defaults domain. This is the list
    /// used by `CoreDataMigrationInputReader` for a source snapshot.
    static let standardDefaultsKeys: [String] = [
        "AWSCredentials",
        "AppLog_CleanShutdown",
        "MacSystemAudioCaptureEnabled",
        "PlatformDeviceVendorIdentifier",
        "PreferredAudioInputUID",
        "SavedEnhancedSummaries",
        "SavedEnhancedSummariesMigrationVersion",
        "SelectedAIEngine",
        "SelectedAIModel",
        "WatchAutoSync",
        "WatchBatteryAware",
        "WatchIntegrationEnabled",
        "aiEngineSelectionMigrated_v1.3",
        "allowInsecurePublicAIEndpoints",
        "appleIntelligenceToOnDeviceLLMMigrated_v1.4",
        "autoSyncMode",
        "awsAccessKey",
        "awsBedrockMaxTokens",
        "awsBedrockModel",
        "awsBedrockModelMigrated_v1.3",
        "awsBedrockProfileName",
        "awsBedrockSessionToken",
        "awsBedrockTemperature",
        "awsBedrockUseProfile",
        "awsBucketName",
        "awsRegion",
        "awsSecretAccessKey",
        "awsSecretKey",
        "bisonnotes.mac.settings.selectedPane",
        "chunkOverlap",
        "comedyModeEnabled",
        "comedyModeStyle",
        "currentlyDownloadingModelId",
        "enableAWSBedrock",
        "enableAWSTranscribe",
        "enableFluidAudio",
        "enableGoogleAIStudio",
        "enableLiveTranscription",
        "enableMistralAI",
        "enableOllama",
        "enableOnDeviceLLM",
        "enableOpenAICompatible",
        "enableWhisper",
        "enableWhisperKit",
        "fileProtectionDowngradeMigration_v1.11.1",
        "fluidAudioDownloadedModelVersion",
        "fluidAudioLocalSpeakerLabelsEnabled",
        "fluidAudioModelDownloaded",
        "fluidAudioSelectedLocalSpeakerLabelMethod",
        "fluidAudioSelectedModelVersion",
        "googleAIStudioAPIKey",
        "googleAIStudioMaxTokens",
        "googleAIStudioModel",
        "googleAIStudioModelNamesMigrated_v1",
        "googleAIStudioTemperature",
        "hasAskedLocationPermission",
        "hasCompletedFirstSetup",
        "hasCompletedInitialLaunch",
        "hasCompletedInitialSetup",
        "hasSeeniCloudPrompt",
        "iCloudActiveManifestMigrationCompletedV2",
        "iCloudBackupIncludeAudioFiles",
        "iCloudBackupIncludeSensitiveSettings",
        "iCloudBackupIncludeSettings",
        "iCloudBackupStateSignatureV1",
        "iCloudLastSuccessfulRoutineSyncV1",
        "iCloudLegacySummaryDiscoveryCompletedV1",
        "iCloudLegacySummaryRecordsAbsentAtV2",
        "iCloudPendingDeletionMarkersV1",
        "iCloudPendingImportedAudioRemovalsV1",
        "iCloudPendingLocalOnlyRemovalsV1",
        "iCloudPendingSummaryRemovalsV1",
        "iCloudPendingTranscriptRemovalsV1",
        "iCloudQuarantinedBackupRecordNamesV2",
        "iCloudQuarantinedLegacySummaryRecordNamesV2",
        "iCloudSensitiveBackupDefaultMigrated_v1.4",
        "iCloudSyncEnabled",
        "iCloudSyncNextEligibleDateV1",
        "isLocationTrackingEnabled",
        "lastAutoBackupDate",
        "lastGeneratedTitle",
        "lastSyncDate",
        "legacyOnDeviceSubSixGBMigration_v2.0",
        "llamaCppModelCleanup_v2.4",
        "llamaCppRemovalMigration_v2.4",
        "maxChunkDuration",
        "maxTranscriptionTime",
        "mistralAPIKey",
        "mistralBaseURL",
        "mistralMaxTokens",
        "mistralModel",
        "mistralSupportsJsonResponseFormat",
        "mistralTemperature",
        "mistralTranscribeDiarize",
        "mistralTranscribeLanguage",
        "mistralTranscribeModel",
        "mlxModelTierRepair_v2.4",
        "mlxSwiftContextTokens",
        "mlxSwiftExperimentalEnabled",
        "mlxSwiftInFlightDownloadModelID",
        "mlxSwiftMaxTokens",
        "mlxSwiftModelId",
        "mlxSwiftRepeatPenalty",
        "mlxSwiftTemperature",
        "mlxSwiftTopK",
        "mlxSwiftTopP",
        "ollamaContextTokens",
        "ollamaMaxTokens",
        "ollamaModelName",
        "ollamaPort",
        "ollamaServerURL",
        "ollamaTemperature",
        "onDeviceLLMEnableExperimentalModels",
        "onDeviceLLMMaxTokens",
        "onDeviceLLMMinP",
        "onDeviceLLMNameMigration_v1.5",
        "onDeviceLLMRepeatPenalty",
        "onDeviceLLMSelectedModel",
        "onDeviceLLMTemperature",
        "onDeviceLLMTopK",
        "onDeviceLLMTopP",
        "openAIAPIKey",
        "openAICompatibleAPIKey",
        "openAICompatibleBaseURL",
        "openAICompatibleManualFormat",
        "openAICompatibleManualFormatOverride",
        "openAICompatibleMaxTokens",
        "openAICompatibleModel",
        "openAICompatibleTemperature",
        "openAISummarizationBaseURL",
        "openAISummarizationMaxTokens",
        "openAISummarizationModel",
        "openAISummarizationTemperature",
        "processedWatchRecordingIds",
        "removedModelsMigrated_v1.8",
        "removedProviderSelectionsMigrated_v2.3",
        "removedProviderSelectionsMigrated_v2.5",
        "selectedTranscriptionEngine",
        "shouldPerformFullSyncOnStartup",
        "showAppleIntelligenceMigrationAlert",
        "showLlamaCppRemovalAlert",
        "showOllamaMigrationAlert",
        "showParakeetMigrationSettings",
        "showTranscriptionProgress",
        "showWhisperKitRemovedAlert",
        "showWhisperKitSwitchedToParakeet",
        "summarizationTimeout",
        "summaryDetailLevel",
        "summaryThinkingLevel",
        "transcriptCleanupEnabled",
        "unifiedICloudSyncEnabled",
        "user_preference_time_format",
        "whisperKitModelDownloaded",
        "whisperKitModelPath",
        "whisperKitRemovedMigration_v1.8",
        "whisperKitSelectedModel",
        "whisperPort",
        "whisperProtocol",
        "whisperServerURL"
    ]

    /// The Action Button intent uses the app group rather than the main
    /// application defaults domain. It is device-local and must not be copied
    /// as library metadata.
    static let appGroupDefaultsKeys = [
        "actionButtonShouldStartRecording"
    ]

    /// Dynamic keys with an app-owned prefix. These are validated by
    /// `LibrarySettingsCatalog.definition(for:)` when concrete keys are read.
    static let dynamicKeyPrefixes = [
        "KeychainSecretStore.revision.",
        "migrated_unavailable_"
    ]

    static var allExactKeys: [String] {
        (standardDefaultsKeys + appGroupDefaultsKeys).sorted()
    }
}
